config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :index] do
    post 'downgrade_account' => 'users#downgrade_account', as: :downgrade_account
  end
  resources :wikis
  resources :charges, only: [:new, :create]
  

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborations
  has_many :collaborated_wikis, through: :collaborations, source: :wiki
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  after_create :initialize_user

  def admin?
    role == 'admin'
  end

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def initialize_user
    self.update_attributes(role: 'standard')
  end

  def upgrade_account
    self.update_attributes(role: 'premium')
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  validates :user, presence: true
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true

  scope :private_wikis, -> (user) { where(private: true) }
  scope :public_wikis, -> (user) { where(private: false) }

  def public?
    self.private == false
  end

  def private?
    self.private == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def user_not_authorized
    flash[:notice] = "You must be signed in to perform that action"
    redirect_to new_user_session_path
  end
end

app/controllers/charges_controller.rb
class ChargesController < ActionController::Base

  before_action :validate_role

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Account - #{current_user.name}",
      amount: default_amount
    }
  end

  def create
    #Set default ammount to $15 for Premium Account
    @amount = 15_00
    customer = Stripe::Customer.create(
      email: current_user.email,
      card:  params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: default_amount,
      description: "Premium Account - #{current_user.email}",
      currency: 'usd'
    )

    # flash[:success] = "#{current_user.email}, is now a Premium Member!"
    current_user.upgrade_account
    redirect_to user_path(current_user)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private

  def default_amount
    amount = 15_00
    amount
  end

  def validate_role
    if current_user
      if current_user.role == 'standard'
        true
      else
        redirect_to user_path(current_user)
        flash[:error] = "#{current_user.name} is already a Premium Member"
      end
    else
      redirect_to new_user_session_path
      flash[:notice] = "You must be signed in to perform that action"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @wikis = @user.wikis.public_wikis(@user)
    @private_wikis = Wiki.private_wikis(@user)
    @collaborated_wikis = @user.collaborated_wikis
  end

  def update
  end

  def downgrade_account
    Wiki.private_wikis(current_user).update_all(private: false)
    current_user.update_attributes(role: 'standard')
    redirect_to edit_user_registration_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_action :find_wiki, except: [:new, :create, :index]

  def index
    @wikis = Kaminari.paginate_array(policy_scope(Wiki)).page(params[:page])
  end

  def show
    @collaborators = @wiki.collaborators
  end

  def new
    @users = User.all
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build( wiki_params )
    @user = @wiki.user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was sucessfully created"
      redirect_to @user
    else
      flash[:error] = "Wiki could not be saved, please try again"
      render :new
    end
  end

  def edit
    @user = @wiki.user
    @users = User.all
  end

  def update
    @user = @wiki.user

    if @wiki.update_attributes( wiki_params )
      flash[:notice] = "Wiki was successfully updated"
      redirect_to @wiki

    else
      flash[:error] = "Wiki could not be updated, please try again"
      render :edit
    end
  end

  def destroy
    @user = @wiki.user

    if @wiki.destroy
      flash[:notice] = "Wiki was successfully deleted"
      redirect_to @user
    else
      flash[:error] = "Wiki could not be deleted, please try again"
      redirect_to @user
    end
  end


  private

  def find_wiki
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki
  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, collaborator_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = { fenced_code_blocks: true, prettify: true, line_numbers: true }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper

#Check whether user is a premium subscriber or an admin
  def premium_or_admin(user)
    unless user == nil
      if user.role == 'premium' || current_user.role == 'admin'
        true
      else
        false
      end
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.haml
.row
  .col-md-4
    %h2 Blocipedia Free
    %ul
      %li
        Create Unlimited Public Wikis
      %li
        View and Edit Other Public Wikis
  .col-md-4
    %h2 Blocipedia Premium
    %h3 All of Blocipedia Free
    %ul
      %li
        Create Unlimited Private Wikis
      %li
        Collaborate and Share Private Wikis
= form_tag charges_path do
  %h4 Click the Button!
  %script.stripe-button{"data-amount" => @stripe_btn_data[:amount], "data-description" => @stripe_btn_data[:description], "data-key" => @stripe_btn_data[:key], :src => "https://checkout.stripe.com/checkout.js"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocipedia
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path}Blocipedia
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.nav-tabs
            %li
              = link_to "Home", root_path
            %li
              = link_to "Browse Wikis", wikis_path
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to (current_user.name || current_user.email), user_path(current_user)
            - else
              %li
                = link_to "Sign In", new_user_session_path
            - if current_user
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :role => "button"}
                  User Options
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    = link_to "Edit User Info", edit_user_registration_path
                  %li
                    = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign Up", new_user_registration_path
    .container
      - if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-danger{"data-dismiss" => "alert", :type => "button"}
          \×
          \#{flash[:error]}
      - elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:alert]
      = yield

app/views/users/_user.html.haml
.container
  .row
    .col-md-6
      %p= link_to user.name, user_path(user)

app/views/users/index.html.haml
%h1 Users
- @users.each do |user|
  %p 
    = link_to user.name, user_path(user.id)

app/views/users/show.html.haml
.container.user
  .user-text
    - if current_user != @user
      %h1
        = @user.name
  .wiki-box
    .wiki-header
      %h2 Public Wikis
    = render @wikis
  .row
    .col-md-4.col-md-offset-5.user-btns
      - if current_user == @user
        = link_to "New Wiki", new_wiki_path(@user, @wiki), class: 'btn btn-success'
      - if current_user.role == 'standard'
        = link_to "Upgrade to Premium", new_charge_path, class: 'btn btn-success'
  - if current_user.role == 'admin' || (current_user.role == 'premium' && current_user == @user)
    .wiki-box
      .wiki-header
        %h2 Private Wikis
      = render @private_wikis

app/views/welcome/about.html.haml
.row
  .col-md-4
    %h1 About Blocipedia

app/views/welcome/index.html.haml
.container
  .container.header-cont
    .heading-cont
      %h1 Blocipedia
.container.cont-border
  .jumbotron.jumbo-content
    %h2 Create and Share Markdown Wikis
    %br/
    - if current_user == nil
      = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'
    - else
      = link_to "Sign In", new_user_session_path, class: 'btn btn-primary'
.container
  .row
    .col-md-4
      .container.cat-headers
        .jumbotron.action-text
          %h2= link_to "Explore", wikis_path
    .col-md-4
      .container.cat-headers
        .jumbotron.action-text
          %h2= link_to "Create", new_wiki_path
    .col-md-4
      .container.cat-headers
        .jumbotron.action-text
          - if current_user && premium_or_admin(current_user)
            %h2= link_to "Share", user_path(current_user)
          - else
            %h2= link_to "Share", new_charge_path

app/views/wikis/_form.html.haml
= form_for [@wiki] do |f|
  - if wiki.errors.any? 
    .alert.alert-danger
      %h4
        There are  #{ pluralize(wiki.errors.count, "error") } 
      %ul
        - wiki.errors.full_messages.each do |msg|
          %li 
            = msg
  .row
    .col-md-9.col-md-offset-2
      %h2 Please Use Markdown Text for Wikis
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', placeholder: "Enter wiki title"
      .form-group
        = f.label :body
        = f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body"
      .form-group
        - if premium_or_admin(current_user)
          = f.check_box :private
          %strong Private
      .form-group
        - if premium_or_admin(current_user)
          = f.label :collaborators
          = f.collection_check_boxes(:collaborator_ids, @users, :id, :name, class: 'check_box')
      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/wikis/_private_wiki.html.haml
.container
  .row
    .col-md-6.col-md-offset-2
      = link_to (markdown_to_html private_wiki.title), wiki_path(wiki)
    .col-md-1
      - if policy(wiki).destroy?
        link_to "Delete", [wiki], method: :delete
          %br/

app/views/wikis/_wiki.html.haml
.container
  .row
    .col-md-6.col-md-offset-2
      = link_to (markdown_to_html wiki.title), wiki_path(wiki)
    .col-md-1
      - if policy(wiki).update?
        = link_to "Edit", edit_wiki_path(wiki)
    .col-md-1
      -if policy(wiki).destroy?
        = link_to "Delete", [wiki], method: :delete

app/views/wikis/edit.html.haml
%h1 Edit Wiki
= render partial: 'form', locals: { wiki: @wiki }

app/views/wikis/index.html.haml
%h1 Wikis
= render @wikis
.pagination_links
  = paginate @wikis

app/views/wikis/new.html.haml
%h1 Create a New Wiki
= render partial: 'form', locals: {wiki: @wiki} 

app/views/wikis/show.html.haml
.container
  .row
    .col-md-3
      - if premium_or_admin(current_user)
        %h3 Collaborators
        = render @collaborators
    .col-md-6
      %h1= markdown_to_html @wiki.title
      %p= markdown_to_html @wiki.body
      - if policy(@wiki).update?
        = link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success'